# maltego-trx-unicode-exceptions
Passing Unicode characters to the Maltego TRX Python Library when running local transforms results in a UnicodeEncodeError exception in the handler.py when it tries to print the response to stdout
